name: Generate API endpoints

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build
      run: ./scripts/gen-and-update-pages.sh

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v29.0.4
      with:
        files: ./pages/*

    - name: Add files
      uses: maxgfr/github-commit-push-file@main
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        commit_name: 'docs: update API endpoints'
